dist: bionic

install:
  - sudo apt update -qq
  # aspell
  - sudo apt-get install aspell
  # proselint
  - sudo pip install proselint

script: 
  - cat README.md | aspell --list
  - proselint README.md
